artifacts_root: artifacts


data_ingestion:
  root: artifacts/data_ingestion
  source_url: 'https://github.com/chirag-garg9/datasets/raw/main/ezyZip.zip'
  local_data_file: artifacts/data_ingestion/books.zip
  unzip_directory: artifacts/data_ingestion

data_validation:
  root: artifacts/data_validation
  status_file: artifacts/data_validation/status.txt
  all_required_files: ['train', 'test']

data_transformation:
  root: artifacts/data_transformation
  data_path: artifacts/data_ingestion/train/train.jsonl
  data_path_test: artifacts/data_ingestion/test/test.jsonl
  tokenizer_name: pszemraj/long-t5-tglobal-base-sci-simplify

model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation
  model_ckpt: pszemraj/long-t5-tglobal-base-sci-simplify

model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts\\data_ingestion\\test\\test.jsonl
  model_path: artifacts/model_trainer/scibert-ML/DL-model
  tokenizer_path: artifacts/model_trainer/tokenizer
  metric_file_name: artifacts/model_evaluation/metrics.csv